version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: "daily"
    groups:
      vuepress:
        patterns:
          - "vuepress*"
          - "@vuepress/*"

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "daily"
