name-template: "Version $NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "New Features"
    labels:
      - "feat"
  - title: "Fixes and Improvements"
    labels:
      - "fix"
      - "refactor"
  - title: "Documentation Updates"
    labels:
      - doc
      - docs
  - title: "Maintenance"
    labels:
      - "ci"
      - "repo"
      - "chore"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What's Changed

  $CHANGES

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - feat
      - minor
  default: patch
