#! /bin/bash

_gittool_bash_autocomplete() {
    local word=${COMP_WORDS[COMP_CWORD]}

    local completions
    completions="$(git-tool complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)"
    if [ $? -ne 0 ]; then
        completions=""
    fi

    COMPREPLY=( $(compgen -W "$completions" -- "$word") )
}

complete -F _gittool_bash_autocomplete gt git-tool