name: Install grcov
description: Installs grcov using the published release binaries
inputs:
  version:
    description: The version of grcov to install, or `latest` for the latest version.
    required: false
    default: latest

  github-token:
    description: The GitHub token which will be used to download releases (helps avoid rate limiting)
    required: true

runs:
  using: node12
  main: "index.js"
