name: "Nix"
on:
  push:
jobs:
  flake:
    name: "Flake"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build .# -j auto -L
      - run: nix flake check .# -j auto -L
