name: Release Changelog

on:
  push:
    branches:
      - main

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
