name: Test Changes
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-3 libdbus-1-dev

      - name: Get Rust Nightly
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install grcov
        uses: actions-rs/install@v0.1
        with:
          crate: grcov
          version: latest
          use-tool-cache: true

      - name: Check out code
        uses: actions/checkout@v1

      - uses: Swatinem/rust-cache@v1

      # - uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       target
      #       !target/*/**.gcda
      #     key: ${{ runner.os }}-cargo-${{ steps.rust.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Prepare Git for Tests
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"

      - name: Run tests
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"

      - name: Collect code coverage
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Upload code coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
