name: Test Changes
on:
  push:
    paths-ignore:
      - "docs/**"
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.run_on }}
    strategy:
      fail-fast: true
      matrix:
        include:
          # Windows builds
          - arch: amd64
            os: windows
            run_on: windows-latest
            target: x86_64-pc-windows-gnu
          # Linux builds
          - arch: amd64
            run_on: ubuntu-latest
            os: linux
            target: x86_64-unknown-linux-gnu
          # Apple MacOS builds
          - arch: amd64
            run_on: macos-latest
            os: darwin
            target: x86_64-apple-darwin

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-3 libdbus-1-dev
        if: matrix.os == 'linux'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Rust caching
        uses: Swatinem/rust-cache@v1

      - name: Get Rust Nightly
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true

      - name: cargo install grcov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov

      - name: Prepare Git for Tests
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"

      - name: grcov
        uses: actions-rs/grcov@v0.1

      - name: codecov upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
