name: Test Changes
on:
  push:
    paths-ignore:
      - "docs/**"
env:
  GRCOV_VERSION: 0.7.1

jobs:
  test:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.run_on }}
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        coverage: [false]
        include:
          # Windows builds
          - arch: amd64
            os: windows
            run_on: windows-latest
            target: x86_64-pc-windows-msvc
          - arch: i386
            run_on: windows-latest
            os: windows
            target: i686-pc-windows-msvc
            experimental: true
          # Linux builds
          - arch: amd64
            run_on: ubuntu-latest
            os: linux
            target: x86_64-unknown-linux-gnu
            coverage: true
          - arch: i386
            os: linux
            run_on: ubuntu-latest
            target: i686-unknown-linux-gnu
            experimental: true
          # Apple MacOS builds
          - arch: amd64
            run_on: macos-latest
            os: darwin
            target: x86_64-apple-darwin

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-3 libdbus-1-dev
        if: matrix.os == 'linux'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Rust caching
        uses: Swatinem/rust-cache@v1

      - name: Cache grcov binary
        uses: actions/cache@v1
        if: matrix.coverage
        with:
          path: ~/.cargo/bin/grcov
          key: ${{ runner.os }}-grcov-${{ env.GRCOV_VERSION }}

      - name: Get Rust Nightly
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
          components: llvm-tools-preview

      - name: cargo install grcov
        if: matrix.coverage
        run: if [[ ! -e ~/.cargo/bin/grcov ]]; then cargo install grcov --version $GRCOV_VERSION; fi

      - name: Prepare Git for Tests
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"
          git config --global init.defaultBranch "main"

      - name: cargo test
        run: cargo test --all-features --no-fail-fast --target ${{ matrix.target }}
        env:
          RUSTFLAGS: "-Zinstrument-coverage"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_CROSS: "1"

      - name: grcov
        run: grcov . --binary-path target/debug/deps/ -s . -t lcov --ignore-not-existing --llvm --ignore '../**' --ignore '/*' --ignore 'C:/' -o ./lcov.info
        if: matrix.coverage

      - name: codecov upload
        uses: codecov/codecov-action@v1
        if: matrix.coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
