name: Test Changes
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0

      - name: cache ~/.cargo
        uses: Swatinem/rust-cache@v1

      - name: rustup install
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: cargo clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: --all-targets --all-features

      - name: cargo fmt --check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --check --all

  test-platforms:
    name: ${{ matrix.os }}-${{ matrix.arch }}-test
    runs-on: ${{ matrix.run_on }}
    continue-on-error: ${{ matrix.experimental || false }}

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        include:
          - arch: amd64
            os: windows
            run_on: windows-latest
            target: x86_64-pc-windows-msvc

          - arch: amd64
            run_on: ubuntu-20.04
            os: linux
            target: x86_64-unknown-linux-gnu
            coverage: true
            setup: |
              sudo apt-get update
              sudo apt-get install -y libdbus-1-3 libdbus-1-dev
          # - arch: "386"
          #   os: linux
          #   run_on: ubuntu-20.04
          #   target: i686-unknown-linux-gnu
          #   experimental: true
          #   skiptests: true
          #   setup: |
          #     sudo apt-get update
          #     sudo apt-get install -y libdbus-1-3 libdbus-1-dev
          - arch: "arm64"
            os: linux
            run_on: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            experimental: true
            skiptests: true
            setup: |
              sudo apt-get update
              sudo apt-get install -y gcc-aarch64-linux-gnu lld

              # Ensure that the libgcc
              sudo ln -s /usr/aarch64-linux-gnu/lib/libgcc_s.so.1 /usr/aarch64-linux-gnu/lib/libgcc_s.so
            flags: --no-default-features

          - arch: amd64
            run_on: macos-latest
            os: darwin
            target: x86_64-apple-darwin
          - arch: arm64
            run_on: macos-latest
            os: darwin
            target: aarch64-apple-darwin
            experimental: true
            skiptests: true

    steps:
      - name: setup dependencies
        run: ${{ matrix.setup }}
        if: matrix.setup

      - uses: actions/checkout@v3

      - name: cache ~/.cargo
        uses: Swatinem/rust-cache@v1

      - name: rustup install nightly
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: git config
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"
          git config --global init.defaultBranch "main"

      - name: cargo build
        uses: actions-rs/cargo@v1.0.3
        if: matrix.skiptests
        with:
          command: build
          args: --target ${{ matrix.target }} ${{ matrix.flags }}

      - name: cargo test
        uses: actions-rs/cargo@v1.0.3
        if: "!matrix.skiptests && !matrix.coverage"
        with:
          command: test
          args: --no-fail-fast --target ${{ matrix.target }} ${{ matrix.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cargo test +coverage
        uses: actions-rs/tarpaulin@v0.1
        if: "!matrix.skiptests && matrix.coverage"
        with:
          args: --no-fail-fast --target ${{ matrix.target }} ${{ matrix.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: get secrets - codecov
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://vault.sierrasoftworks.com
          method: jwt
          path: github-actions
          role: pull_request
          jwtGithubAudience: https://vault.sierrasoftworks.com
          secrets: |
            secrets/data/repos/SierraSoftworks/git-tool/public/codecov token | CODECOV_TOKEN;

      - name: codecov upload
        uses: codecov/codecov-action@v3
        if: matrix.coverage || false
        with:
          token: ${{ env.CODECOV_TOKEN }}

  test-done:
    name: Tests Complete
    needs:
      - test-platforms
      - code-quality
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Tests Complete for All Platforms"
