name: Test Changes
on:
  push:
    paths-ignore:
      - "docs/**"
env:
  GRCOV_VERSION: 0.7.1

jobs:
  test:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.run_on }}
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        include:
          - arch: amd64
            os: windows
            run_on: windows-latest
            target: x86_64-pc-windows-gnu
          - arch: "386"
            run_on: windows-latest
            os: windows
            target: i686-pc-windows-gnu
            extension: .exe
            experimental: true
            cross: true
          - arch: amd64
            run_on: ubuntu-latest
            os: linux
            target: x86_64-unknown-linux-gnu
            coverage: true
          - arch: "386"
            os: linux
            run_on: ubuntu-latest
            target: i686-unknown-linux-gnu
            experimental: true
            cross: true
          - arch: arm64
            run_on: ubuntu-latest
            os: linux
            target: aarch64-unknown-linux-gnu
            experimental: true
            cross: true
          - arch: amd64
            run_on: macos-latest
            os: darwin
            target: x86_64-apple-darwin
          - arch: arm64
            run_on: macos-latest
            os: darwin
            target: aarch64-apple-darwin
            experimental: true
            cross: true

    steps:
      - name: apt-get install libdbus
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-3 libdbus-1-dev
        if: matrix.os == 'linux'

      - uses: actions/checkout@v2

      - name: cache ~/.cargo
        uses: Swatinem/rust-cache@v1

      - name: rustup install nightly
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
          components: llvm-tools-preview

      - name: cargo install grcov
        uses: SierraSoftworks/setup-grcov@v1
        if: matrix.coverage || false
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: git config
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"
          git config --global init.defaultBranch "main"

      - name: cross test
        uses: actions-rs/cargo@v1
        if: matrix.cross
        with:
          use-cross: true
          command: test
          args: --all-features --no-fail-fast --target ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cargo test
        uses: actions-rs/cargo@v1
        if: "!matrix.cross"
        with:
          command: test
          args: --all-features --no-fail-fast --target ${{ matrix.target }}
        env:
          RUSTFLAGS: -Zinstrument-coverage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: grcov
        run: grcov . --binary-path target/${{ matrix.target }}/debug/deps/ -s . -t lcov --ignore-not-existing --ignore '../**' --ignore '/*' --ignore 'C:/' -o ./lcov.info
        if: matrix.coverage || false

      - name: codecov upload
        uses: codecov/codecov-action@v1
        if: matrix.coverage || false
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
